# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target ‘PUBG Hub’ do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PUBGCompanion
pod 'BTNavigationDropdownMenu'
pod 'SwiftyJSON', '~> 3.1.4’
pod 'DropDown'
pod 'NVActivityIndicatorView'
pod 'Google-Mobile-Ads-SDK'
pod ‘SwiftGifOrigin’, ‘~> 1.6.1’
pod 'LUExpandableTableView', '~> 2.1'
pod 'SDWebImage/GIF'
pod 'Siren', :git => 'https://github.com/ArtSabintsev/Siren.git', :branch => 'swift3.1'
pod 'Alamofire', '~> 4.5'
pod 'AlamofireImage', '~> 3.3'
pod 'Kanna', '~> 2.1.0'
pod 'YouTubePlayer'
pod 'GoogleSignIn'
pod 'GoogleAPIClientForREST/YouTube'
pod 'Tabman', '~> 1.0'
pod 'RevealingSplashView'

end
